### ISSUE TITLE
Maximum number of allowable file uploads has been exceeded

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub-modules-gallery#12]
This error outputs after upload all files, an error/warning should be triggered before like **"You can only upload X files at the same time"**
```
{
    "readyState": 4,
    "responseText": "<br />\n<b>Warning</b>:  Maximum number of allowable file uploads has been exceeded in <b>Unknown</b> on line <b>0</b><br />\n<br />\n<b>Warning</b>:  Maximum number of allowable file uploads has been exceeded in <b>Unknown</b> on line <b>0</b><br />\n<br />\n<b>Warning</b>:  Maximum number of allowable file uploads has been exceeded in <b>Unknown</b> on line <b>0</b><br />\n<br />\n<b>Warning</b>:  Maximum number of allowable file uploads has been exceeded in <b>Unknown</b> on line <b>0</b><br />
    "status": 200,
    "statusText": "OK"
}
```

**Comment by BastusIII** [comment]
Hi,

this is caused by a php configuration. You should increase ``max_file_uploads`` in ``php.ini`` to avoid that.

As php destroys the JSON response by prepending its errors in plaintext, the errors cannot be parsed properly. In a production environment, php should be configured to NOT do that. Please have a look at https://stackoverflow.com/questions/12872515/php-warning-demolishes-json-response. The post describes how to do that.

Kind regards, 
Basti
